AWSTemplateFormatVersion: '2010-09-09'
Parameters:

  StageName:
    Type: String
    Default: 'dev'
    Description: 'Stage name for the API Gateway deployment'

  LambdaFunctionName:
    Type: String
    Default: 'event-processor-lambda'
    Description: 'Name of the Lambda function'

  S3BucketName:
    Type: String
    Description: 'S3 bucket name where the Lambda code is stored'
    Default: 'lambda-deployment-event-bridge'

  EventProcessorLambdaS3Key:
    Type: String
    Description: 'S3 key for the Lambda code'

  LambdaTimeout:
    Type: Number
    Default: 120
    Description: 'Timeout for the Lambda function in seconds'

  EventBusName:
    Type: String
    Description: 'Name of the EventBridge bus'

  DownloadFileLambdaArn:
    Type: String

  DownloadFileLambdaName:
    Type: String

Resources:

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
          - Effect: 'Allow'
            Principal:
              Service: 'scheduler.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaDynamoDBPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:*'
                Resource: '*'
        - PolicyName: 'LambdaEventBridgePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'events:PutEvents'
                Resource: !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${EventBusName}'
        - PolicyName: 'LambdaInvokePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'lambda:InvokeFunction'
                Resource: !Ref DownloadFileLambdaArn

  LambdaExecutionScheduleRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'scheduler.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaEventBridgePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'events:PutEvents'
                Resource: !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${EventBusName}'
        - PolicyName: 'LambdaInvokePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'lambda:InvokeFunction'
                Resource: !GetAtt LambdaFunction.Arn



  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: 'org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest'
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref EventProcessorLambdaS3Key
      Runtime: 'java21'
      Timeout: !Ref LambdaTimeout
      MemorySize: 512
      Environment:
        Variables:
          MAIN_CLASS: 'br.com.fredericci.EventProcessor'
          EVENT_BUS_NAME: !Ref EventBusName
          DOWNLOAD_FILE_LAMBDA_ARN: !Ref DownloadFileLambdaArn

  EventProcessorInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref DownloadFileLambdaName
      Action: 'lambda:InvokeFunction'
      Principal: 'lambda.amazonaws.com'
      SourceArn: !GetAtt LambdaFunction.Arn

  EventProcessorLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: 'lambda:InvokeFunction'
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt EventProcessorRule.Arn

  EventProcessorRule:
    Type: 'AWS::Events::Rule'
    Properties:
      EventBusName: !Ref EventBusName
      EventPattern:
        source:
          - "custom.api.gateway"
        detail-type:
          - "InputEvent"
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: "EventProcessorTarget"

  MyScheduledLambda:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: "Schedule to invoke a Lambda function daily"
      GroupName: "default" # Or a custom schedule group name
      Name: "MyDailyLambdaSchedule"
      FlexibleTimeWindow:
        Mode: "OFF"
      ScheduleExpression: "cron(0 12 * * ? *)" # Runs daily at 12:00 PM UTC
      #ScheduleExpression: "cron(*/2 * * * ? *)" # Runs daily at 12:00 PM UTC
      State: "ENABLED"
      Target:
        Arn: !GetAtt LambdaFunction.Arn # ARN of the Lambda function to invoke
        Input: "{\"key\": \"value\"}" # Optional input payload for the target
        RoleArn: !GetAtt LambdaExecutionScheduleRole.Arn # ARN of the IAM role for Scheduler

  LambdaLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${LambdaFunction}'
      RetentionInDays: 3
